/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.visao;
import main.java.objetos.*;
import main.java.controle.UsuarioControle;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class JAdminUsuarios extends javax.swing.JFrame {

    public JAdminUsuarios() {
        initComponents();
        rtAviso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        btUserR = new javax.swing.JButton();
        btUserU = new javax.swing.JButton();
        btUserD = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        rtCpf = new javax.swing.JLabel();
        cxUser = new javax.swing.JTextField();
        rtAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Admin", "Colaborador", "Email"
            }
        ));
        jScrollPane1.setViewportView(tbUsers);

        btUserR.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserR.setText("CONSULTAR");
        btUserR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserRActionPerformed(evt);
            }
        });

        btUserU.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserU.setText("ATUALIZAR");

        btUserD.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserD.setText("DELETAR");

        btVoltar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        rtCpf.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rtCpf.setText("CPF:");

        cxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxUserActionPerformed(evt);
            }
        });

        rtAviso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rtAviso.setForeground(new java.awt.Color(255, 51, 51));
        rtAviso.setText("Não encontrado.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btUserR)
                .addGap(18, 18, 18)
                .addComponent(btUserU)
                .addGap(18, 18, 18)
                .addComponent(btUserD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rtAviso)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtAviso))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUserR)
                    .addComponent(btUserU)
                    .addComponent(btUserD)
                    .addComponent(btVoltar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxUserActionPerformed

    private void btUserRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserRActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbUsers.getModel();
        Usuario u = null;
        
        if("".equals(cxUser.getText())) compTabela();
        else{
            for(Usuario u2 : UsuarioControle.getUsuarios()){
                if(u2.getCpf().equals(cxUser.getText())) u = u2;
            }
            
            if(u == null) rtAviso.setVisible(true);
            else{
                modelo.setRowCount(0);
                modelo.insertRow(0, new Object[]{u.getNome(), u.getCpf(),
                                                 (u.getAdm_flag() ? "Sim" : "Nao"),
                                                 (u.getColab_flag() ? "Sim" : "Nao"),
                                                 u.getEmail()
                                                 });
            }
        }
    }//GEN-LAST:event_btUserRActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        JAdmin ja = new JAdmin();
        int opt = JOptionPane.showConfirmDialog(
                                                null,
                                                "Deseja voltar?",
                                                "Retorno",
                                                JOptionPane.YES_NO_OPTION);
        
        if(opt == 0){
            this.dispose();
            ja.setVisible(true);
        }
    }//GEN-LAST:event_btVoltarActionPerformed
    
    private void compTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tbUsers.getModel();
        int linha = 0;
        
        for(Usuario u : UsuarioControle.getUsuarios()){
            modelo.insertRow(linha, new Object[]{u.getNome(), u.getCpf(),
                                                 (u.getAdm_flag() ? "Sim" : "Nao"),
                                                 (u.getColab_flag() ? "Sim" : "Nao"),
                                                 u.getEmail()
                                                 });
            linha++;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUserD;
    private javax.swing.JButton btUserR;
    private javax.swing.JButton btUserU;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField cxUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtAviso;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JTable tbUsers;
    // End of variables declaration//GEN-END:variables
}
