package main.java.visao;

import main.java.controle.MenuControle;
import javax.swing.JOptionPane;


public class JAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JAdmin
     */
    public JAdmin() {
        initComponents();
        setLocationRelativeTo(null); // Inicia a janela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtGer = new javax.swing.JLabel();
        btGerUser = new javax.swing.JButton();
        btGerPl = new javax.swing.JButton();
        btGerPll = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtGer.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rtGer.setText("GERENCIAR");

        btGerUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btGerUser.setText("USUARIOS");
        btGerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerUserActionPerformed(evt);
            }
        });

        btGerPl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btGerPl.setText("PALESTRAS");
        btGerPl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerPlActionPerformed(evt);
            }
        });

        btGerPll.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btGerPll.setText("PALESTRANTES");
        btGerPll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerPllActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGerPl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerPll, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(rtGer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rtGer)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btGerUser)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btGerPl)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btGerPll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int opt = JOptionPane.showConfirmDialog(
                rootPane,
                "Deseja sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
                );
        
        if(opt == 0){
            dispose();
            MenuControle.setUsuarioAtual(null);
            MenuControle.menuInicial.setVisible(true);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void btGerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerUserActionPerformed
        JAdminUsuarios jau = JAdminUsuarios.getJAdminUsuarios();
        
        this.dispose();
        jau.setVisible(true);
    }//GEN-LAST:event_btGerUserActionPerformed

    private void btGerPlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerPlActionPerformed
        JAdminPalestra jap = JAdminPalestra.getJAdminPalestra();
        
        this.dispose();
        jap.setVisible(true);
    }//GEN-LAST:event_btGerPlActionPerformed

    private void btGerPllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerPllActionPerformed
        JAdminPll japll = JAdminPll.getJAdminPll();
        
        this.dispose();
        japll.setVisible(true);
    }//GEN-LAST:event_btGerPllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerPl;
    private javax.swing.JButton btGerPll;
    private javax.swing.JButton btGerUser;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel rtGer;
    // End of variables declaration//GEN-END:variables
}
