/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.visao;
import main.java.objetos.*;
import main.java.controle.*;
import main.java.exceptions.DelUserAtualException;

import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;

public final class JAdminUsuarios extends javax.swing.JFrame implements JAdminInterface{
    UsuarioControle uc = UsuarioControle.getUsuarioControle();
    Usuario u = null;
    private static JAdminUsuarios insJAdminUsuarios;
    
    ActionListener apagaAviso = new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent evt){
            rtAviso.setVisible(false);
            tempo.stop();
        }
    };
            
    Timer tempo = new Timer(1500, apagaAviso);
    
    private JAdminUsuarios() {
        initComponents();
        rtAviso.setVisible(false);
        compTabela();
    }
    
    public static JAdminUsuarios getJAdminUsuarios(){
        if(insJAdminUsuarios == null) insJAdminUsuarios = new JAdminUsuarios();
        
        return insJAdminUsuarios;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        btUserR = new javax.swing.JButton();
        btUserU = new javax.swing.JButton();
        btUserD = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        rtCpf = new javax.swing.JLabel();
        cxUser = new javax.swing.JTextField();
        rtAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Admin", "Colaborador", "Email"
            }
        ));
        jScrollPane1.setViewportView(tbUsers);

        btUserR.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserR.setText("CONSULTAR");
        btUserR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserRActionPerformed(evt);
            }
        });

        btUserU.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserU.setText("ATUALIZAR");
        btUserU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserUActionPerformed(evt);
            }
        });

        btUserD.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btUserD.setText("DELETAR");
        btUserD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserDActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        rtCpf.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rtCpf.setText("CPF:");

        cxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxUserActionPerformed(evt);
            }
        });
        cxUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxUserKeyPressed(evt);
            }
        });

        rtAviso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rtAviso.setForeground(new java.awt.Color(255, 51, 51));
        rtAviso.setText("Não encontrado.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btUserR)
                .addGap(18, 18, 18)
                .addComponent(btUserU)
                .addGap(18, 18, 18)
                .addComponent(btUserD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(rtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rtAviso)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtAviso))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUserR)
                    .addComponent(btUserU)
                    .addComponent(btUserD)
                    .addComponent(btVoltar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxUserActionPerformed

    private void btUserRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserRActionPerformed
        ler();
    }//GEN-LAST:event_btUserRActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btUserUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserUActionPerformed
        atualizar();
    }//GEN-LAST:event_btUserUActionPerformed

    private void btUserDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserDActionPerformed
        deletar();
    }//GEN-LAST:event_btUserDActionPerformed

    private void cxUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxUserKeyPressed
        ler(evt);
    }//GEN-LAST:event_cxUserKeyPressed
    
    @Override
    public void compTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tbUsers.getModel();
        int linha = 0;
        
        modelo.setRowCount(0);
        
        for(Usuario u1 : UsuarioControle.getUsuarios()){
            modelo.insertRow(linha, new Object[]{u1.getNome(), u1.getCpf(),
                                                 (u1.getAdm_flag() ? "Sim" : "Nao"),
                                                 (u1.getColab_flag() ? "Sim" : "Nao"),
                                                 u1.getEmail()
                                                 });
            linha++;
        }
        
    }
    
    @Override
    public void ler(){
        DefaultTableModel modelo = (DefaultTableModel) tbUsers.getModel();
        u = null;
        
        if("".equals(cxUser.getText())) compTabela();
        else{
            modelo.setRowCount(0);
            
            for(Usuario u2 : UsuarioControle.getUsuarios()){
                if(u2.getCpf().equals(cxUser.getText())) u = u2;
            }
            
            if(u == null){ rtAviso.setVisible(true); tempo.start();}
            else{
                modelo.insertRow(0, new Object[]{u.getNome(), u.getCpf(),
                                                 (u.getAdm_flag() ? "Sim" : "Nao"),
                                                 (u.getColab_flag() ? "Sim" : "Nao"),
                                                 u.getEmail()
                                                 });
            }
        }
    }
    
    @Override
    public void ler(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) ler();
    }
    @Override
    public void deletar(){
        boolean check = false;
        u = uc.buscarCpf(cxUser.getText());
        
        try{
            if(u == null){ rtAviso.setVisible(true); tempo.start();}
            else{
                check = uc.deletar(u);

                if(check)
                    JOptionPane.showMessageDialog(null, "Deletado com sucesso");

                compTabela();
            }
        } catch(DelUserAtualException duae){
            JOptionPane.showMessageDialog(null, "Nao se pode deletar usuario atual",
                    "Erro delecao de usuario", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public void atualizar(){
        JCheckBox cbAdmin = new JCheckBox("Admin"),
                  cbColab = new JCheckBox("Colaborador");
        String msg = "Atualizar permissoes";
        Object[] parente = {msg, cbAdmin, cbColab};
        int opt = 0;
        
        u = uc.buscarCpf(cxUser.getText());
        
        if(u == null){ rtAviso.setVisible(true); tempo.start();}
        else{
            opt = JOptionPane.showConfirmDialog(null, parente, "Permissoes",
                    JOptionPane.OK_CANCEL_OPTION);
            
            if(opt == 0){
                u.setAdm_flag(cbAdmin.isSelected());
                u.setColab_flag(cbColab.isSelected());
                
                UsuarioControle.getUsuarios().set(UsuarioControle.getUsuarios().indexOf(u), u);
            }
            
            compTabela();
        }
    }
    
    @Override
    public void voltar(){
        JAdmin ja = new JAdmin();
        int opt = JOptionPane.showConfirmDialog(
                                                null,
                                                "Deseja voltar?",
                                                "Retorno",
                                                JOptionPane.YES_NO_OPTION);
        
        if(opt == 0){
            this.dispose();
            ja.setVisible(true);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JAdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUserD;
    private javax.swing.JButton btUserR;
    private javax.swing.JButton btUserU;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField cxUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtAviso;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JTable tbUsers;
    // End of variables declaration//GEN-END:variables
}
