/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.visao;

import javax.swing.JOptionPane;
import main.java.controle.MenuControle;
import main.java.objetos.Usuario;

/**
 *
 * @author gp51f
 */
public class JColaborador extends javax.swing.JFrame {
    
     private Usuario user;

    /**
     * Creates new form JColaborador
     */
    public JColaborador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtColab = new javax.swing.JLabel();
        btCriarPalestra = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btPalestra = new javax.swing.JButton();
        btInscricao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtColab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rtColab.setText("COLABORADOR");

        btCriarPalestra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCriarPalestra.setText("Criar Palestra");
        btCriarPalestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarPalestraActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btPalestra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btPalestra.setText("Palestras");
        btPalestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPalestraActionPerformed(evt);
            }
        });

        btInscricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btInscricao.setText("Inscrições");
        btInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(rtColab, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCriarPalestra, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(btPalestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtColab)
                .addGap(40, 40, 40)
                .addComponent(btCriarPalestra)
                .addGap(18, 18, 18)
                .addComponent(btPalestra)
                .addGap(18, 18, 18)
                .addComponent(btInscricao)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCriarPalestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarPalestraActionPerformed
        if(validarColab()) criarPalestra();
    }//GEN-LAST:event_btCriarPalestraActionPerformed

    private void btPalestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPalestraActionPerformed
        mostrarTabela();
    }//GEN-LAST:event_btPalestraActionPerformed

    private void btInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscricaoActionPerformed
        mostrarIncricoes();
    }//GEN-LAST:event_btInscricaoActionPerformed

    public void mostrarIncricoes(){
        JColabInscricoes.geraJColabInscricoes().setVisible(true);
        dispose();
    }
    public void mostrarTabela(){
        JColabPalestra.geraColabPalestra().setVisible(true);
        dispose();
    }
    
    
    
    //metodo set do atributo user
    public void setUser(Usuario user){
        this.user = user;
    }
    
    //metodo get do atributo user
    public Usuario getUser(){
        return user;
    }
    
    public void criarPalestra(){
        MenuControle.menuColabCriarPalestra.setVisible(true);
        dispose();
    }
    
    public boolean validarColab(){
        user = MenuControle.getUsuarioAtual();
        if(this.user == null || !(this.user.getColab_flag())){
            JOptionPane.showMessageDialog(
                    this,
                    "Permitido apenas para colaboradores",
                    "ACESSO NEGADO!",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "SAIR",
                JOptionPane.YES_NO_OPTION);
        
        if(resp == 0){
            MenuControle.setUsuarioAtual(null);
            dispose();
            MenuControle.menuInicial.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarPalestra;
    private javax.swing.JButton btInscricao;
    private javax.swing.JButton btPalestra;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel rtColab;
    // End of variables declaration//GEN-END:variables
}
