/// src/main/java/visao/JPalestras.java
package main.java.visao;

import main.java.objetos.Palestra;
import main.java.controle.PalestraControle;
import main.java.controle.MenuControle;

import java.awt.Font;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main.java.controle.UsuarioControle;


public class JPalestra extends javax.swing.JFrame {
    private static JPalestra jPalestraUnic = null;    
    private List<Integer> palestraCod = new LinkedList<>();
    private boolean completo;
    private boolean inscritas;
        
    public JPalestra() {
        initComponents();
        
        setLocationRelativeTo(null); // Inicia a janela centralizada
        setExtendedState(MAXIMIZED_BOTH);
    }

    public static JPalestra getJPalestra(){
        if (jPalestraUnic == null) {
            jPalestraUnic = new JPalestra();
        }
        return jPalestraUnic;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPalestra = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        mbOpcoes = new javax.swing.JMenu();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbPalestra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbPalestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Local", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPalestra.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPalestra.setRowHeight(30);
        tbPalestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPalestraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPalestra);
        if (tbPalestra.getColumnModel().getColumnCount() > 0) {
            tbPalestra.getColumnModel().getColumn(0).setPreferredWidth(350);
            tbPalestra.getColumnModel().getColumn(1).setPreferredWidth(300);
            tbPalestra.getColumnModel().getColumn(2).setPreferredWidth(100);
        }
        //minhas configs
        tbPalestra.getColumnModel().getColumn(2).setCellRenderer(
            new DefaultTableCellRenderer(){{setHorizontalAlignment(SwingConstants.CENTER);}}
        );
        tbPalestra.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        //fim

        mbOpcoes.setText("Opções");

        miVoltar.setText("Voltar...");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbOpcoes.add(miVoltar);

        barraMenu.add(mbOpcoes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inscritas) listarTabPalestrasI();
        else if(completo) listarTabPalestrasC();
    }//GEN-LAST:event_formWindowActivated

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void tbPalestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPalestraMouseClicked
        if(inscritas) selecTabI();
        else if(completo) selecTabC();
    }//GEN-LAST:event_tbPalestraMouseClicked

    public void listarTabPalestrasC(){
        DefaultTableModel modelo = (DefaultTableModel) tbPalestra.getModel();       

        int lin = 0;
        modelo.setRowCount(lin);
        
        palestraCod.clear();
        
        for(Palestra p : PalestraControle.getPalestras()){
            modelo.insertRow(lin, new Object[]{p.getTitulo(), p.getLocal(), p.getData()});
            palestraCod.add(p.getCodigo());
            lin++;
        }
    }
    public void listarTabPalestrasI(){
        DefaultTableModel modelo = (DefaultTableModel) tbPalestra.getModel();       

        int lin = 0;
        modelo.setRowCount(lin);
        
        palestraCod.clear();
        
        for(Palestra p : MenuControle.getUsuarioAtual().getPalestras()){
            modelo.insertRow(lin, new Object[]{p.getTitulo(), p.getLocal(), p.getData()});
            palestraCod.add(p.getCodigo());
            lin++;
        }
    }
    
    public void selecTabC(){
        int linSelec = tbPalestra.getSelectedRow();

        if(linSelec == -1) return;
        
        int palestraSelecCod = palestraCod.get(linSelec);
        
        Palestra palestraSelec = null;

        for(Palestra p : PalestraControle.getPalestras()){
            if (p.getCodigo() == palestraSelecCod) {
                palestraSelec = p;
                break;
            }
        }

        if(palestraSelec != null){
            String mensagem = "Título: " + palestraSelec.getTitulo() +
                              "\nLocal: " + palestraSelec.getLocal() +
                              "\nData: " + palestraSelec.getData() +
                              "\nHora: " + palestraSelec.getHora() +
                              "\nVagas: " + palestraSelec.getVagas();
            
            int o = JOptionPane.showOptionDialog(
                    null, mensagem, "Detalhes da Palestra",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, 
                    null, new String[]{"Voltar", "Se Inscrever"}, "Voltar"
            );

            if(o == 1) UsuarioControle.autoInscricao(palestraSelec);
        }
    }
    public void selecTabI(){
        int linSelec = tbPalestra.getSelectedRow();

        if(linSelec == -1) return;
        
        int palestraSelecCod = palestraCod.get(linSelec);
        
        Palestra palestraSelec = null;

        for(Palestra p : MenuControle.getUsuarioAtual().getPalestras()){
            if (p.getCodigo() == palestraSelecCod) {
                palestraSelec = p;
                break;
            }
        }

        if(palestraSelec != null){
            String mensagem = "Título: " + palestraSelec.getTitulo() +
                              "\nLocal: " + palestraSelec.getLocal() +
                              "\nData: " + palestraSelec.getData() +
                              "\nHora: " + palestraSelec.getHora() +
                              "\nVagas: " + palestraSelec.getVagas();
            
            JOptionPane.showMessageDialog(null, mensagem, "Detalhes da Palestra", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    public void voltar(){
        MenuControle.getMenuUser().setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPalestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbOpcoes;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tbPalestra;
    // End of variables declaration//GEN-END:variables

    void setCompleto(boolean b) {
        this.completo = b;
    }

    void setInscritas(boolean b) {
        this.inscritas = b;
    }
}
